easy_admin:
    site_name: 'Wild Circus'
    entities:
        Booking:
            class: App\Entity\Booking
            list:
                actions:
                    - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
                    - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-warning'}
        Performer:
            class: App\Entity\Performer
            list:
                actions:
                    - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
                    - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-warning'}
            form:
                fields:
                    - { property: 'performerFile', type: 'vich_image' }
        Show:
            class: App\Entity\Show
            list:
                actions:
                    - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
                    - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-warning'}